language: python
python:
  - "3.8.7"
addons:
  firefox: "89.0"
before_install:
  - sudo apt-get install xvfb
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.29.1/geckodriver-v0.29.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.29.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
  - sleep 5 # give xvfb some time to start
install:
  - make deps
script:
  - make test
